"""Generate the README segmentation overlay from NSCLC-Radiomics DICOM data."""

# ruff: noqa: E501

from __future__ import annotations

import argparse
import base64
from pathlib import Path

import cv2
import numpy as np
import pydicom

from medical_image_segmentation.inference import segment_lungs_ct
from medical_image_segmentation.visualization.overlays import overlay


def encode_png(array: np.ndarray) -> str:
    """Encode an image array as an embeddable PNG data payload."""
    encoded_input = cv2.cvtColor(array, cv2.COLOR_RGB2BGR) if array.ndim == 3 else array
    success, buffer = cv2.imencode(".png", encoded_input)
    if not success:
        raise OSError("Could not encode the overlay panel as PNG")
    return base64.b64encode(buffer.tobytes()).decode("ascii")


def load_middle_slice(series: Path) -> tuple[int, np.ndarray]:
    """Load the middle DICOM instance and calibrate pixels to HU."""
    instances = []
    for path in series.rglob("*.dcm"):
        dataset = pydicom.dcmread(str(path))
        instances.append((int(getattr(dataset, "InstanceNumber", 0)), dataset))
    if not instances:
        raise FileNotFoundError(f"No DICOM instances found under {series}")
    instances.sort(key=lambda item: item[0])
    number, dataset = instances[len(instances) // 2]
    pixels = dataset.pixel_array.astype(np.float32)
    hu = pixels * float(getattr(dataset, "RescaleSlope", 1))
    hu += float(getattr(dataset, "RescaleIntercept", 0))
    return number, hu


def build_svg(slice_number: int, image_hu: np.ndarray) -> tuple[str, np.ndarray]:
    """Run segmentation and return a self-contained three-panel SVG."""
    mask = segment_lungs_ct(image_hu)
    windowed = np.clip((image_hu + 1350.0) / 1500.0, 0.0, 1.0)
    original = (windowed * 255).astype(np.uint8)
    blended = (np.clip(overlay(windowed, mask, alpha=0.42), 0, 1) * 255).astype(
        np.uint8
    )
    mask_rgb = np.zeros((*mask.shape, 3), dtype=np.uint8)
    mask_rgb[mask] = (34, 211, 238)
    original_png, mask_png, overlay_png = map(
        encode_png, (original, mask_rgb, blended)
    )
    svg = f"""<svg xmlns="http://www.w3.org/2000/svg" width="1200" height="540" viewBox="0 0 1200 540" role="img" aria-labelledby="title description">
  <title id="title">LUNG1-001 lung segmentation overlay</title>
  <desc id="description">Classical lung segmentation generated by medical-image-segmentation from axial DICOM slice {slice_number} of NSCLC-Radiomics.</desc>
  <defs>
    <linearGradient id="bg" x1="0" y1="0" x2="1" y2="1"><stop stop-color="#101b27"/><stop offset="1" stop-color="#071018"/></linearGradient>
    <filter id="shadow"><feDropShadow dx="0" dy="8" stdDeviation="10" flood-opacity=".35"/></filter>
  </defs>
  <rect width="1200" height="540" rx="22" fill="url(#bg)"/>
  <text x="42" y="48" fill="#e5edf5" font-family="Inter,Segoe UI,sans-serif" font-size="25" font-weight="700">Lung Segmentation · LUNG1-001</text>
  <text x="42" y="76" fill="#8fa3b8" font-family="Inter,Segoe UI,sans-serif" font-size="13">NSCLC-Radiomics · axial slice {slice_number} · deterministic HU + connected-components pipeline</text>
  <g filter="url(#shadow)"><rect x="38" y="102" width="344" height="350" rx="12" fill="#020405"/><rect x="428" y="102" width="344" height="350" rx="12" fill="#020405"/><rect x="818" y="102" width="344" height="350" rx="12" fill="#020405"/></g>
  <image href="data:image/png;base64,{original_png}" x="41" y="105" width="338" height="338"/>
  <image href="data:image/png;base64,{mask_png}" x="431" y="105" width="338" height="338"/>
  <image href="data:image/png;base64,{overlay_png}" x="821" y="105" width="338" height="338"/>
  <g fill="#dbe7f1" font-family="Inter,Segoe UI,sans-serif" font-size="15" font-weight="600" text-anchor="middle"><text x="210" y="480">Input CT</text><text x="600" y="480">Lung mask</text><text x="990" y="480">Prediction overlay</text></g>
  <circle cx="866" cy="511" r="6" fill="#ef4444"/><text x="880" y="516" fill="#9fb2c4" font-family="Inter,Segoe UI,sans-serif" font-size="11">Segmented lung</text>
  <text x="42" y="516" fill="#688399" font-family="Inter,Segoe UI,sans-serif" font-size="10">Research demonstration · not for clinical use · doi:10.7937/K9/TCIA.2015.PF0M9REI</text>
</svg>
"""
    return svg, mask


def main() -> None:
    """Parse paths, execute segmentation, and write the SVG artifact."""
    parser = argparse.ArgumentParser()
    parser.add_argument("series", type=Path, help="LUNG1-001 directory or series")
    parser.add_argument("output", type=Path, help="Destination SVG")
    args = parser.parse_args()
    number, image_hu = load_middle_slice(args.series)
    svg, mask = build_svg(number, image_hu)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(svg, encoding="utf-8")
    print(
        f"slice={number} mask_pixels={int(mask.sum())} "
        f"mask_percent={mask.mean() * 100:.2f} output={args.output}"
    )


if __name__ == "__main__":
    main()
